### ISSUE TITLE
Fails to find Management IDs for Serial Numbers

### ISSUE THREAD

**Issue by moose-juice** [chrisgzim/Jamf-API-Recovery-Lock-by-Group#10]
Regardless of whether I run the script against a Smart Group, Static Group, or provide serial numbers directly in the swiftDialog window, it fails to find management IDs for the serial numbers. 

The script is clearly reading the serial numbers from the Smart Group, so connectivity to the API is working - however, it seems to be an issue when retrieving information on the computers themselves.

When I open /var/tmp/recoverylock.csv it is empty.

I will try and dig deeper into the script to find the source of the issue.

**Comment by chrisgzim** [comment]
Thank you for reaching out! That makes sense, so it might have to do more with getting the management ids from the first API call. 

Out of curiosity, what is the integer you are putting into the number of computers field? Are you using the total number of managed computers? 

I noticed that sometimes older records show up, and that throws off the workflow. I wanted to do a bulk grab of all of the management ids to avoid having to run multiple API calls per machine. I might have to rebuild and use that logic for some more consistency in the workflow.

**Comment by chrisgzim** [comment]
I am going to close this one as it is similar to our other issue we have open, but here is a lazy fix for now: https://github.com/chrisgzim/Jamf-API-Recovery-Lock-by-Group/blob/development/swiftdialog_jproapilock_lazy.sh
